export const images = {
    imageNormalSquare:require('./source/commonSquare.png'),
    imageSpecialSquare:require('./source/specialSquare.png'),
    lineVertical:require('./source/lineVertical.png'),
    lineHorizontal:require('./source/lineHorizontal.png'),
    startSquare:require('./source/Start.png'),
    Map1_1:require('./source/Map1_1.png'),
    Map1_2:require('./source/Map1_2.png'),
    Map1_3:require('./source/Map1_3.png'),
    Map2_1:require('./source/Map2_1.png'),
    Map2_2:require('./source/Map2_2.png'),
    Map2_3:require('./source/Map2_3.png'),
    Logo:require('./source/Logo.png'),
    background:require('./source/Background.png'),
    Cloud1:require('./source/Cloud1.png'),
    Cloud2:require('./source/Cloud2.png'),
    imageHome:require('./source/imageHome.png'),
    borderView:require('./source/BorderView.png'),
    FrameItems:require('./source/FrameItems.png'),
    FrameNameItems:require('./source/FrameNameItems.png'),
    firstBanner:require('./source/firstBanner.png'),
    videoImage:require('./source/videoImage.png'),
    listCardImage:require('./source/listCardImage.png'),
    FrameActive:require('./source/FrameActive.png'),
    FrameInActive:require('./source/FrameInActive.png'),
    banner1:require('./source/banner_01.png'),
    banner2:require('./source/banner_02.png'),
    banner3:require('./source/banner_03.png'),

}
export type ImageTypes = keyof typeof images